package things.form.channelsystems;

import utilities.property.IProperty;

/**
 * A need that is generated by a channelsystem
 * 
 * @author borah
 *
 */
public class ChannelNeed implements IProperty<Float> {

	private String name;
	private IChannelSystem channelSystem;
	private String csn;

	public ChannelNeed(String name, IChannelSystem channelSystem) {
		this.name = name;
		this.channelSystem = channelSystem;
		this.csn = channelSystem.name();
	}

	public String getName() {
		return csn + "_" + name;
	}

	public Float defaultValue() {
		return 1f;
	}

	@Override
	public Class<? super Float> getType() {
		return float.class;
	}

	public IChannelSystem getChannelSystem() {
		return this.channelSystem;
	}

	public String getChannelSystemName() {
		return this.csn;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj instanceof ChannelNeed in) {
			return this.name.equals(in.name) && this.csn.equals(in.csn);
		}
		return super.equals(obj);
	}

	@Override
	public int hashCode() {
		return this.name.hashCode() + this.csn.hashCode();
	}

	@Override
	public String toString() {
		return "<:" + this.csn + ":" + this.name + ":>";
	}

	@Override
	public String getPropertyName() {
		return this.getName();
	}

}
