package things.form.channelsystems;

import _utilities.property.IProperty;
import thinker.concepts.application.IConceptAssociationInfo;
import thinker.mind.memory.IFeelingReason;
import thinker.mind.perception.IPerceptor;

/**
 * A need that is generated by a channelsystem. 1f should be full satisfaction,
 * while 0f should be complete depletion
 * 
 * @author borah
 *
 */
public interface IChannelNeed extends IProperty<Float>, IConceptAssociationInfo, IPerceptor, IFeelingReason {

	@Override
	default PerceptorType getPerceptorType() {
		return PerceptorType.NEED;
	}

	/** Returns the name of this channelneed's channel system */
	String getChannelSystemName();

	/** Returns the actual channel system this need is associated with */
	IChannelSystem getChannelSystem();

	/** The simple name of this channel need */
	String getName();

}
